application: go-faces
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /js
  static_dir: js
- url: /reset.*
  script: _go_app
- url: /thumbs.*
  script: _go_app
- url: /.*
  script: _go_app
